[Term Entry] Python:NumPy Math Methods log10
Codecademy/codepedia-content pull request #4773
Opened 2024-06-13 15:19 UTC by andersooi

### Description

- Added new term entry for Python:NumPy Math Methods `log10`

### Issue Solved

Closes #4710 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

2024-06-19 14:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=4773) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4773) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: andersooi<br/>:x: cigar-galaxy82<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4773) it.</sub>

2024-06-21 17:07 UTC, cigar-galaxy82 requested changes
Hi, I have suggested a few changes please modify

2024-06-21 17:09 UTC, cigar-galaxy82 commented
Hi @andersooi 

The entry is well written, thank you for contributing to Codecademy docs.

I have suggested one change, please modify

2024-06-22 22:08 UTC, cigar-galaxy82 approved these changes

2024-06-24 09:08 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @andersooi! 😃 

The entry is ready to be merged 🚀

2024-06-24 09:13 UTC, merged