[Term Entry] C++ vector .back()
Codecademy/codepedia-content pull request #5014
Opened 2024-08-09 19:06 UTC by SaviDahegaonkar

### Description

### Issue Solved
Closes #4984 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-21 16:37 UTC, avdhoottt requested changes
Hey @SaviDahegaonkar, I have suggested some changes. Please make them!!

2024-08-21 16:37 UTC, avdhoottt commented on content/cpp/concepts/vectors/terms/back/back.md
> +The below example shows the use of `.back()` method in c++ vectors, here `numbers` is a vector which has 5 elements in it and it displays the last element in the vector with the help of the `.back()`
Put this line after the `Example` heading.

2024-08-21 16:37 UTC, avdhoottt commented on content/cpp/concepts/vectors/terms/back/back.md
> +```
Add a line here saying that the following is the output of the above code. You can write it as you want.

2024-08-21 16:37 UTC, avdhoottt commented on content/cpp/concepts/vectors/terms/back/back.md
> +This codebyte example shows that how a last element in the vector in accessed and modified using the `back()` method.
Add this after the Codebyte heading.

2024-10-15 09:14 UTC, SaviDahegaonkar commented
Hello @avdhoottt, Sorry for the late response
I have made the changes :)

Thanks,
Savi

2024-11-11 12:11 UTC, closed without merging