[Term Entry] Add math-fabs method to math module on Codecademy docs
Codecademy/codepedia-content pull request #5131
Opened 2024-08-30 00:12 UTC by theosjones

### Description

Added math.fab(s) method topic to the Math module for Python in Codecademy Docs.

### Issue Solved

Closes [Term Entry] Python math-module math.fabs() #5031

### Type of Change

Added new documentation to Codecademy Docs.

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

2024-08-30 00:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/docs?pullRequest=5131) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5131) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5131) it.</sub>

2024-08-31 11:55 UTC, cigar-galaxy82 requested changes

2024-08-31 11:55 UTC, cigar-galaxy82 commented on content/python/concepts/math-module/terms/math-fabs/math-fabs.md
> +The `math.fabs()` function takes in a number value and returns its absolute value as a float. A non-negative number is returned and thus, a negative number is first negated. Unlike math.abs(), the va
```suggestion
The `math.fabs()` function takes in a numeric value and returns its absolute value as a float. Unlike `math.abs()`, the value is always converted to a float value. Any other data type except a number will return a TypeError.
```

2024-08-31 11:55 UTC, cigar-galaxy82 commented on content/python/concepts/math-module/terms/math-fabs/math-fabs.md
> +The following examples run and use the `math.fabs()` function to return the absolute value of a number as a float:
```suggestion
Run the following code to understand how the `math.fabs()` function works:
```

2024-08-31 11:56 UTC, cigar-galaxy82 commented
Hi @theosjones thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

2024-09-10 23:38 UTC, cigar-galaxy82 approved these changes

2024-09-11 08:57 UTC, mamtawardhani approved these changes
Thank you for contributing to Codecademy Docs @theosjones 😄 

The entry is ready to be merged! 🚀

2024-09-11 09:00 UTC, merged