classes article created
Codecademy/codepedia-content pull request #9
Opened 2021-04-26 16:55 UTC by pablonnaoji

Seeking feedback on my Python classes article.

2021-04-26 16:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/codepedia-content?pullRequest=9) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/codepedia-content?pullRequest=9) before we can accept your contribution.<br/><hr/>**Paul.Nnaoji** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/codepedia-content?pullRequest=9) it.</sub>

2021-04-26 17:00 UTC, pablonnaoji commented
I went ahead and signed the contributor license agreement. Do let me know if you need anything else.

2021-04-27 07:12 UTC, sonnynomnom reviewed
left some comments! fix and we gucci!

2021-04-27 07:12 UTC, sonnynomnom commented on content/python/encyclopedia/classes-in-python.md
> +```employee.py
```
```py
```

2021-04-27 07:12 UTC, sonnynomnom commented on content/python/encyclopedia/classes-in-python.md
> +
extra line here (delete)

2021-04-27 07:12 UTC, sonnynomnom commented on content/python/encyclopedia/classes-in-python.md
> +
two linebreaks here (just do one)

2021-04-27 07:12 UTC, sonnynomnom commented on content/python/encyclopedia/classes-in-python.md
> +class Employee(object):
```py
class Employee(object):
    name = "Sam"
    company = "ILoveCode Inc."
    age = 30
    is_on_vacation = True

    def working(self,employee_name):
       self.name = employee_name
       print(employee_name + " is working")
```

2021-04-27 07:12 UTC, sonnynomnom commented on content/python/encyclopedia/classes-in-python.md
> +# What are Classes in Python?
```
# Classes in Python
```

2021-04-27 07:12 UTC, sonnynomnom commented on content/python/encyclopedia/classes-in-python.md
> +## An example of an "Employee" Class
```
## Example
```

2021-04-27 07:12 UTC, sonnynomnom commented on content/python/encyclopedia/classes-in-python.md
> +    def working(self,employee_name):
add a space after comma:

```
def working(self, employee_name):
```

2021-04-27 07:12 UTC, sonnynomnom commented on content/python/encyclopedia/classes-in-python.md
> +   >>> Blake is working
we shouldn't do triple >>> here. maybe just:

```
# Output: Blake is working
```

2021-04-27 21:47 UTC, sammillersmith requested changes
Good start! Please take a look at our edits and resubmit, and you should be good to go!
Quick reminder to use the template and content standards in the [documentation folder](https://github.com/Codecademy/codepedia-content/tree/main/documentation)--those should answer any questions you might have about the metadata

2021-04-27 21:47 UTC, sammillersmith commented on content/python/encyclopedia/classes-in-python.md
> +  - "What are Classes in Python?"
The "Subjects" field is being used as an additional tagging system. Please pick tags from Subjects that are already listed on Author here: https://author.codecademy.com/browse/categories.

2021-04-27 21:47 UTC, sammillersmith commented on content/python/encyclopedia/classes-in-python.md
> +Tags:
Please use tags listed here: https://author.codecademy.com/browse/tags
"python" is on that list, but the other two are not

2021-04-27 21:47 UTC, sammillersmith commented on content/python/encyclopedia/classes-in-python.md
> +---
Please add the Title field, [as in the template](https://github.com/Codecademy/codepedia-content/blob/main/documentation/encyclopedia-entry-template.md)

2021-04-27 21:47 UTC, sammillersmith commented on content/python/encyclopedia/classes-in-python.md
> +---
Please add the Catalog Content field, [as in the template](https://github.com/Codecademy/codepedia-content/blob/main/documentation/encyclopedia-entry-template.md)

2021-05-03 12:56 UTC, pablonnaoji commented
Thanks for the feedback! I've made the requested changes. Resubmitting now.

2021-05-03 12:56 UTC, closed without merging